/*
 * @Author: cold-x
 * @Date: 2025-05-28 15:04:59
 * @LastEditors: duncy 474647591@qq.com
 * @LastEditTime: 2026-04-13 16:28:20
 * @FilePath: /ling_bao/lib/global/ui/assets.dart
 * @Description: 
 */
///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  ///tab页
  static const String tabVideo = 'assets/global/tab/icon_tab_video.png';
  static const String tabVideoSelected =
      'assets/global/tab/icon_tab_video_selected.png';
  static const String tabImage = 'assets/global/tab/icon_tab_image.png';
  static const String tabImageSelected =
      'assets/global/tab/icon_tab_image_selected.png';
  static const String tabCreate = 'assets/global/tab/icon_tab_create.png';
  static const String tabCreateSelected =
      'assets/global/tab/icon_tab_create.png';
}
